# -------------------------------------------------
# --              FRAMEWORK global.R             --
# -------------------------------------------------
# NOTEs:                                         --
# Program code goes in "program" directory files --
# -------------------------------------------------
# *****        DO NOT EDIT THIS FILE       ***** --
# -------------------------------------------------

suppressPackageStartupMessages({
    library(periscope)
    library(shinyBS)
    library(shinyjs)
    library(lubridate)
    library(yaml)
})

source(paste("program", "global.R", sep = .Platform$file.sep), local = TRUE)
