# -------------------------------------------------
# --              FRAMEWORK server.R             --
# -------------------------------------------------
# NOTEs:                                         --
# Program code goes in "program" directory files --
# -------------------------------------------------
# *****        DO NOT EDIT THIS FILE       ***** --
# -------------------------------------------------

source(paste("program", "server_global.R", sep = .Platform$file.sep),
       local = TRUE)


shinyServer(function(input, output, session) {
    ss_userAction.Log     <- periscope:::fw_get_user_log()

    source(paste("program", "server_local.R", sep = .Platform$file.sep),
           local = TRUE)

    periscope:::fw_server_setup(input, output, session, ss_userAction.Log)

    announcements_file <- get_env_value("announcements_file")
    announce_setup     <- NULL

    if (file.exists(announcements_file)) {
        tryCatch({
            announce_setup <- read_yaml(announcements_file)

            if (any(is.null(announce_setup),
                    !is.list(announce_setup),
                    length(announce_setup) < 1)) {
                logwarn(glue("File {announcements_file} is empty or corrupted. Announcements will be ignored"))
                announce_setup <- NULL
            }
        },
        error = function(e) {
            logwarn(glue("Could not parse {announcements_file} due to {e$message}"))
        })

        if (!is.null(announce_setup)) {
            start_date        <- announce_setup[["start_date"]]
            start_date_format <- announce_setup[["start_date_format"]]
            end_date          <- announce_setup[["end_date"]]
            end_date_format   <- announce_setup[["end_date_format"]]
            style             <- announce_setup[["style"]]
            title             <- announce_setup[["title"]]
            text              <- announce_setup[["text"]]
            auto_close        <- announce_setup[["auto_close"]]

            valid <- TRUE

            if (!is.null(start_date)) {
                if (!is_valid_date_format(start_date, start_date_format)) {
                    if (is.null(start_date_format)) {
                        start_date_format <- ""
                    }
                    logwarn(glue("Announcement 'start_date' value '{start_date}' could not be converted to a valid date",
                                 " with the given 'start_date_format' value: '{start_date_format}' "))
                    valid <- FALSE
                } else {
                    start_date <- as_date(start_date, format = start_date_format)
                }
            }

            if (valid && !is.null(end_date)) {
                if (!is_valid_date_format(end_date, end_date_format)) {
                    if (is.null(end_date_format)) {
                        end_date_format <- ""
                    }
                    logwarn(glue("Announcement 'end_date' value '{end_date}' could not be converted to a valid date",
                                 " with the given 'end_date_format' value: '{end_date_format}' "))
                    valid <- FALSE
                } else {
                    end_date <- as_date(end_date, format = end_date_format)
                }
            }

            if (valid && !(any(is.null(start_date), start_date <= Sys.Date()) &&
                           any(is.null(end_date), Sys.Date() <= end_date))) {
                valid <- FALSE
            }

            valid_styles <- c("info", "danger", "success", "warning")
            style        <- tolower(style)

            if (valid && any(length(style) == 0,
                             style == "",
                             !(tolower(style) %in% valid_styles))) {
                logwarn(glue("Announcement 'style' must be one of {glue_collapse(valid_styles, sep = ',')}."))
                valid <- FALSE
            }

            if (valid && any(is.null(text), text == "")) {
                logwarn("Announcement 'text' value is empty. It must contain non empty text value")
                valid <- FALSE
            }

            if (valid) {
                createAlert(session,
                            "announce",
                            "Announcements",
                            title   = title,
                            content = text,
                            style   = style,
                            append  = FALSE)
                if (all(!is.null(auto_close),
                        !is.numeric(auto_close))) {
                    logwarn(glue("Announcement 'auto_close' value '{auto_close}' is invalid. It must contain numeric value."))
                    auto_close <- NULL
                }

                if (all(!is.null(auto_close),
                        auto_close > 0)) {
                    delay(auto_close * 1000, closeAlert(session, "Announcements"))
                }
            }
        }
    }

    loginfo("%s started with log level <%s>",
            periscope:::fw_get_title(), periscope:::fw_get_loglevel(),
            logger = ss_userAction.Log)
})


# is_valid_date_format
#' Check if passed date with the passed format is valid
#'   Return TRUE if passed value is a valid date
#'
#' @param date_value  - passed date value as string
#' @param date_format - passed date format to be used to parse date with (default = NULL)
#'
#' @return boolean
is_valid_date_format <- function(date_value, date_format = NULL) {
    valid_format <- FALSE

    tryCatch({
        parsed_date <- as_date(date_value, format = date_format)

        if (!is.na(parsed_date)) {
            valid_format <- TRUE
        }
    },
    warning = function(w) {
        logwarn(glue("Could not convert date: '{date_value}' with format: '{date_format}' with error: '{w$message}'",
                      .null = ""))

    },
    error = function(e) {
        logerror(glue("Could not convert date: '{date_value}' with format: '{date_format}' with error : '{e$message}'",
                      .null = ""))
    })

    valid_format
}
